[
  {
    name: "The Gray Borques",
    season: "Q1 2021",
    gamesPlayed: 9,
    wins: 5,
    losses: 2,
    sow: 0,
    sol: 2,
    points: 17,
    goalsFor: 25,
    goalsAgainst: 25
   
  },
  {
    name: "Los Greengoes",
    season: "Q1 2021",
    gamesPlayed: 9,
    wins: 6,
    losses: 3,
    sow: 1,
    sol: 0,
    points: 17,
    goalsFor: 37,
    goalsAgainst: 25
  },
  {
    name: "Gritty Goons",
    season: "Q1 2021",
    gamesPlayed: 9,
    wins: 5,
    losses: 4,
    sow: 1,
    sol: 0,
    points: 14,
    goalsFor: 33,
    goalsAgainst: 35
  },
  {
    name: "North Kariya",
    season: "Q1 2021",
    gamesPlayed: 9,
    wins: 2,
    losses: 7,
    sow: 0,
    sol: 0,
    points: 3,
    goalsFor: 28,
    goalsAgainst: 38
  },
  {
    name: "Pinkie and the Brian...Chambers",
    season: "Q1 2020",
    gamesPlayed: 9,
    wins: 4,
    losses: 5,
    sow: 0,
    sol: 0,
    points: 12,
    goalsFor: 29,
    goalsAgainst: 38
  },
  {
    name: "Blades of Teal",
    season: "Q1 2020",
    gamesPlayed: 10,
    wins: 8,
    losses: 2,
    sow: 0,
    sol: 0,
    points: 24,
    goalsFor: 59,
    goalsAgainst: 29
  },
  {
    name: "Blue Cross Blue Shield",
    season: "Q1 2020",
    gamesPlayed: 9,
    wins: 7,
    losses: 2,
    sow: 0,
    sol: 0,
    points: 21,
    goalsFor: 43,
    goalsAgainst: 28
  },
  {
    name: "The Solo Cups",
    season: "Q1 2020",
    gamesPlayed: 10,
    wins: 5,
    losses: 5,
    sow: 0,
    sol: 0,
    points: 15,
    goalsFor: 38,
    goalsAgainst: 31
  },
  {
    name: "The Empire Strikes Black",
    season: "Q1 2020",
    gamesPlayed: 10,
    wins: 0,
    losses: 10,
    sow: 0,
    sol: 0,
    points: 0,
    goalsFor: 15,
    goalsAgainst: 58
   
  },
  {
    name: "Nick's Wonder Friends",
    season: "Q4 2019",
    gamesPlayed: 12,
    wins: 7,
    losses: 5,
    sow: 0,
    sol: 0,
    points: 21,
    goalsFor: 54,
    goalsAgainst: 48
  },
  {
    name: "Red Army",
    season: "Q4 2019",
    gamesPlayed: 12,
    wins: 7,
    losses: 5,
    sow: 1,
    sol: 0,
    points: 21,
    goalsFor: 53,
    goalsAgainst: 53
  },
  {
    name: "Gold on the Ceiling",
    season: "Q4 2019",
    gamesPlayed: 12,
    wins: 6,
    losses: 5,
    sow: 0,
    sol: 1,
    points: 20,
    goalsFor: 68,
    goalsAgainst: 43
  },
  {
    name: "Pink Cobras",
    season: "Q4 2019",
    gamesPlayed: 12,
    wins: 5,
    losses: 7,
    sow: 0,
    sol: 0,
    points: 19,
    goalsFor: 51,
    goalsAgainst: 61
  },
  {
    name: "Spray Tan Aftermath",
    season: "Q4 2019",
    gamesPlayed: 12,
    wins: 5,
    losses: 7,
    sow: 0,
    sol: 0,
    points: 15,
    goalsFor: 37,
    goalsAgainst: 58
  },
  {
    name: "Ashholes",
    season: "Q3 2019",
    gamesPlayed: 9,
    wins: 6,
    losses: 3,
    sow: 0,
    sol: 0,
    points: 18,
    goalsFor: 41,
    goalsAgainst: 22
  },
  {
    name: "Goldmembers",
    season: "Q3 2019",
    gamesPlayed: 9,
    wins: 6,
    losses: 3,
    sow: 0,
    sol: 0,
    points: 18,
    goalsFor: 47,
    goalsAgainst: 34
  },
  {
    name: "Gritty's Goons",
    season: "Q3 2019",
    gamesPlayed: 9,
    wins: 6,
    losses: 3,
    sow: 1,
    sol: 0,
    points: 17,
    goalsFor: 28,
    goalsAgainst: 26
  },
  {
    name: "Purple Reign",
    season: "Q3 2019",
    gamesPlayed: 9,
    wins: 0,
    losses: 8,
    sow: 0,
    sol: 1,
    points: 1,
    goalsFor: 20,
    goalsAgainst: 54
  },
  {
    name: "Agent Orange",
    season: "Q2 2019",
    gamesPlayed: 11,
    wins: 7,
    losses: 3,
    sow: 0,
    sol: 1,
    points: 22,
    goalsFor: 55,
    goalsAgainst: 42
  },
  {
    name: "Black Magic Badgers",
    season: "Q2 2019",
    gamesPlayed: 11,
    wins: 7,
    losses: 4,
    sow: 0,
    sol: 0,
    points: 21,
    goalsFor: 40,
    goalsAgainst: 42
  },
  {
    name: "The Second Worst Team in Texas",
    season: "Q2 2019",
    gamesPlayed: 11,
    wins: 7,
    losses: 4,
    sow: 0,
    sol: 0,
    points: 21,
    goalsFor: 53,
    goalsAgainst: 31
  },
  {
    name: "Pucks Capacitors",
    season: "Q2 2019",
    gamesPlayed: 11,
    wins: 5,
    losses: 6,
    sow: 0,
    sol: 0,
    points: 14,
    goalsFor: 23,
    goalsAgainst: 46
  },
  {
    name: "Dekes of Hazzard",
    season: "Q2 2019",
    gamesPlayed: 11,
    wins: 2,
    losses: 9,
    sow: 0,
    sol: 0,
    points: 6,
    goalsFor: 28,
    goalsAgainst: 38
  },
  {
    name: "The Worst Team in Texas",
    season: "Q1 2019",
    gamesPlayed: 10,
    wins: 9,
    losses: 1,
    sow: 2,
    sol: 0,
    points: 25,
    goalsFor: 49,
    goalsAgainst: 27
  },
  {
    name: "The Cocks",
    season: "Q1 2019",
    gamesPlayed: 10,
    wins: 8,
    losses: 2,
    sow: 0,
    sol: 0,
    points: 25,
    goalsFor: 53,
    goalsAgainst: 20
  },
  {
    name: "Baby Got Black",
    season: "Q1 2019",
    gamesPlayed: 10,
    wins: 6,
    losses: 3,
    sow: 0,
    sol: 1,
    points: 19,
    goalsFor: 39,
    goalsAgainst: 25
  },
  {
    name: "Silver Foxes",
    season: "Q1 2019",
    gamesPlayed: 10,
    wins: 4,
    losses: 6,
    sow: 0,
    sol: 0,
    points: 12,
    goalsFor: 32,
    goalsAgainst: 43
  },
  {
    name: "Richards Le Rouge",
    season: "Q1 2019",
    gamesPlayed: 10,
    wins: 2,
    losses: 8,
    sow: 0,
    sol: 2,
    points: 8,
    goalsFor: 30,
    goalsAgainst: 49
  },
  {
    name: "Blue Wave",
    season: "Q1 2019",
    gamesPlayed: 10,
    wins: 1,
    losses: 9,
    sow: 1,
    sol: 0,
    points: 2,
    goalsFor: 22,
    goalsAgainst: 61
  },
  {
    name: "Puckin Spice",
    season: "Q4 2018",
    gamesPlayed: 10,
    wins: 8,
    losses: 2,
    sow: 3,
    sol: 0,
    points: 21,
    goalsFor: 49,
    goalsAgainst: 34
  },
  {
    name: "Victorious Secret",
    season: "Q4 2018",
    gamesPlayed: 10,
    wins: 7,
    losses: 3,
    sow: 1,
    sol: 0,
    points: 20,
    goalsFor: 42,
    goalsAgainst: 33
  },
  {
    name: "Coors Light Silver Bullet Love Train",
    season: "Q4 2018",
    gamesPlayed: 10,
    wins: 5,
    losses: 5,
    sow: 0,
    sol: 0,
    points: 15,
    goalsFor: 37,
    goalsAgainst: 34
  },
  {
    name: "Black Squoose",
    season: "Q4 2018",
    gamesPlayed: 10,
    wins: 4,
    losses: 4,
    sow: 0,
    sol: 2,
    points: 14,
    goalsFor: 40,
    goalsAgainst: 33
  },
  {
    name: "Toby's Red Rockets",
    season: "Q4 2018",
    gamesPlayed: 10,
    wins: 3,
    losses: 6,
    sow: 0,
    sol: 0,
    points: 9,
    goalsFor: 21,
    goalsAgainst: 45
  },
  {
    name: "Labattschitcrazies",
    season: "Q4 2018",
    gamesPlayed: 10,
    wins: 2,
    losses: 5,
    sow: 0,
    sol: 2,
    points: 8,
    goalsFor: 27,
    goalsAgainst: 37
  }
]